name: discord_test
description: "A new Flutter project."


publish_to: 'none'
version: 3.0.3

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  adaptive_breakpoints: ^0.1.7
  animations: ^2.0.11
  audio_service: ^0.18.13
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  characters: ^1.3.0
  cloud_firestore: ^4.16.0
  cloud_functions: ^4.7.0
  code_builder: ^4.10.0
  collection: ^1.18.0
  confetti: ^0.7.0
  connectivity: ^3.0.6
  crypto: ^3.0.3
  dart_date: ^1.3.2
  dart_style: ^2.3.6
  date_format: ^2.0.7
  device_preview: ^1.1.0
  dio: ^5.4.2+1
  email_validator: ^2.1.17
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  event_bus_plus: ^0.6.2
  expand_tap_area: ^1.1.1
  expandable_page_view: ^1.0.17
  external_path: ^1.0.3
  file_picker: ^8.0.0+1
  firebase_analytics: ^10.10.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  firebase_core_platform_interface: ^5.0.0
  firebase_crashlytics: ^3.5.0
  firebase_dynamic_links: ^5.5.0
  firebase_messaging: ^14.8.0
  firebase_storage: ^11.7.0
  flutter:
    sdk: flutter
  flutter_device_type: ^0.4.0
  flutter_email_sender: ^6.0.2
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.0.0
  flutter_platform_widgets: ^6.1.0
  flutter_portal: ^1.1.4
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.9
  flutter_timetable: ^1.1.6
  flutter_widgetkit: ^1.0.3
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_it: ^7.6.8
  google_sign_in: ^6.2.1
  gsheets: ^0.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  home_widget: ^0.5.0
  image_picker: ^1.0.7
  in_app_review: ^2.0.9
  indexed_list_view: ^3.0.2
  infinite_listview: ^1.1.0
  injectable: ^2.4.1
  intl: ^0.19.0
  jiffy: ^6.2.1
  jopen: ^0.0.2
  json_annotation: ^4.8.1
  just_audio: ^0.9.37
  linkwell: ^2.0.6
  marquee: ^2.2.3
  marquee_widget: ^1.2.0
  new_version_plus: ^0.0.10
  numberpicker: ^2.1.2
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1
  open_app_file: ^4.0.2
  open_file_plus: ^3.4.1+1
  optimized_cached_image: ^3.0.1
  overlay_support: ^2.1.0
  package_info: ^2.0.2
  path_provider: ^2.1.2
  pedantic: ^1.11.1
  permission_handler: ^11.3.1
  photo_view: ^0.14.0
  profanity_filter: ^2.0.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  scroll_snap_list: ^0.9.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  sentry_flutter: ^7.18.0
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^6.0.0
  skeletons: ^0.0.3
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.1.0
  source_gen: ^1.5.0
  stream_transform: ^2.1.0
  strings: ^3.1.1
  substring_highlight: ^1.0.33
  swipe_to: ^1.0.6
  table_calendar: ^3.0.9
  time: ^2.1.4
  timeago: ^3.6.1
  tuple: ^2.0.2
  uni_links: ^0.5.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.5
  uuid: ^3.0.7
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.7.0
  weekday_selector: ^1.1.0
  xxh64: ^0.0.3+1

dev_dependencies:
  build_runner: ^2.4.9
  flip_card: ^0.7.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  grinder: ^0.9.3
  import_sorter: ^4.6.0
  injectable_generator: ^2.6.1
  intl_utils: ^2.8.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  objectbox_generator: ^2.5.1




flutter:
  uses-material-design: true

  
  assets:
    - assets/

