name: discord_test
description: "A new Flutter project."


publish_to: 'none'
version: 3.0.3

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true

  
  assets:
    - assets/

