name: discord_test
description: "A new Flutter project."


publish_to: 'none'
version: 3.0.3

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  logging: ^1.2.0
  permission_handler: ^11.3.1
  star_menu: ^4.0.1
  system_info: ^1.0.1

  path_provider: any
  http: any
  go_router: ^14.2.1
  flutter_page_transition_plus: ^1.0.2
  animations: ^2.0.11
  eventflux: ^2.2.1
  provider: ^6.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true

  
  assets:
    - assets/

